### ISSUE TITLE
Custom styled Desktop Tab bar

### ISSUE THREAD

**Issue by dt2patel** [hotwax/clienteling#13]
For desktop view the tab bar is an inefficient use of space. instead it should be styled to look like this where they float above the content instead of consuming the entire bottom bar of the display. ￼

<img width="396" alt="Screen Shot 2021-10-14 at 10 37 36 AM" src="https://user-images.githubusercontent.com/60128132/137452064-8d1f5ba6-da55-42dc-87da-1b4070620e93.png">

**Comment by rajatshrm648** [comment]
![abc](https://user-images.githubusercontent.com/63601384/138326185-52cf054e-5373-4d78-9187-0e41acd6f90f.png)
@dt2patel  , Please let me know that its looks good or not , If you want any updates in this so plz let me know.
